[package]
name = "violetj2p-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.20"
syn = "*"

[dependencies.violetj2p-macro-util]
path = "../violetj2p-macro-util"
