[package]
name = "willow-parser"
authors = ["ethgallucci"]
version = "0.1.0"
edition = "2021"

[lib]
name = "willow_parser"
crate-type = ["cdylib"]

[profile.dev]
incremental = true
lto = false
debug-assertions = true
overflow-checks = true
opt-level = 0

[profile.release]
opt-level = 3
overflow-checks = false
strip = "debuginfo"
debug-assertions = false
lto = false
panic = "unwind"
incremental = false


[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
pyo3 = "0.16.5"
serde = { version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
