name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Run Tests and Build if succesful
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test

  docker-build-deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: willowreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t willowreg.azurecr.io/willowapp:${{ github.sha }}
        docker push willowreg.azurecr.io/willowapp:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'willowapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'willowreg.azurecr.io/willowapp:${{ github.sha }}'