[workspace]
members = ["violetj2p-core", "violetj2p-macro", "violetj2p-macro-util"]

[profile.dev]
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
lto = true
debug-assertions = false
overflow-checks = false
